[package]
name = 'ternoa-primitives'
version = '0.1.0'
edition = '2018'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
frame-system = { version = '2.0.0', default-features = false }
sp-application-crypto = { version = '2.0.0', default-features = false }
sp-core = { version = '2.0.0', default-features = false }
sp-runtime = { version = '2.0.0', default-features = false }
sp-std = { version = '2.0.0', default-features = false }

[features]
default = ['std']
std = [
	'frame-system/std',
	'sp-application-crypto/std',
	'sp-core/std',
	'sp-runtime/std',
    'sp-std/std',
]
