[profile.release]
panic = 'unwind'

[workspace]
members = [
    'common',
    'node',
    "node/service",
    'pallets/*',
    'primitives',
    'runtime/chaosnet',
    'runtime/alphanet',
    'runtime/mainnet',
]
