version: '3'

services:
  ternoa:
    image: "ternoa/ternoa-chain:0.2.2"
    command: '--chain test-net --base-path /data --name MyDockerComposeNode'
    user: "0:0" # fix disk permissions by setting the docker user ID to be the one from the host system (typically 1000:1000 or 0:0)
    restart: always
    volumes:
      - /opt/ternoa/node-data:/data
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
      - 9615:9615
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
