
//! Autogenerated weights for `ternoa_transmission_protocols`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-19, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Ternoa-Recommended-Reference-Machine`, CPU: `AMD EPYC 7281 16-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("alphanet-dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/ternoa
// benchmark
// pallet
// --chain=alphanet-dev
// --steps=50
// --repeat=20
// --pallet=ternoa_transmission_protocols
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./output

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

//TODO ADD REAL VALUES
/// Weight functions for `ternoa_transmission_protocols`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> ternoa_transmission_protocols::WeightInfo for WeightInfo<T> {
	fn set_transmission_protocol() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	fn remove_transmission_protocol() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	fn reset_timer() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	fn add_consent() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	fn set_protocol_fee() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
}
