
//! Autogenerated weights for `ternoa_nft`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-19, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Ternoa-Recommended-Reference-Machine`, CPU: `AMD EPYC 7281 16-Core Processor`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("alphanet-dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/ternoa
// benchmark
// pallet
// --chain=alphanet-dev
// --steps=50
// --repeat=20
// --pallet=ternoa_nft
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./output

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `ternoa_nft`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> ternoa_nft::WeightInfo for WeightInfo<T> {
	// Storage: NFT NftMintFee (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT NextNFTId (r:1 w:1)
	// Storage: NFT Nfts (r:0 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn create_nft(s: u32, ) -> Weight {
		Weight::from_ref_time(165_612_000 as u64)
			// Standard Error: 39
			.saturating_add(Weight::from_ref_time(15_717 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(5 as u64))
			.saturating_add(T::DbWeight::get().writes(5 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT Collections (r:1 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn burn_nft(s: u32, ) -> Weight {
		Weight::from_ref_time(104_095_000 as u64)
			// Standard Error: 32
			.saturating_add(Weight::from_ref_time(17_481 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	fn transfer_nft() -> Weight {
		Weight::from_ref_time(55_594_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT DelegatedNFTs (r:0 w:1)
	fn delegate_nft() -> Weight {
		Weight::from_ref_time(60_726_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	fn set_royalty() -> Weight {
		Weight::from_ref_time(53_221_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT NftMintFee (r:0 w:1)
	fn set_nft_mint_fee() -> Weight {
		Weight::from_ref_time(44_664_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT NextCollectionId (r:1 w:1)
	// Storage: NFT Collections (r:0 w:1)
	fn create_collection() -> Weight {
		Weight::from_ref_time(72_446_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	fn burn_collection() -> Weight {
		Weight::from_ref_time(62_317_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	fn close_collection() -> Weight {
		Weight::from_ref_time(56_516_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	fn limit_collection() -> Weight {
		Weight::from_ref_time(72_817_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT Nfts (r:1 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn add_nft_to_collection(s: u32, ) -> Weight {
		Weight::from_ref_time(86_552_000 as u64)
			// Standard Error: 40
			.saturating_add(Weight::from_ref_time(15_906 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT NftMintFee (r:1 w:0)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT NextNFTId (r:1 w:1)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	// Storage: NFT Nfts (r:0 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn create_secret_nft(s: u32, ) -> Weight {
		Weight::from_ref_time(183_555_000 as u64)
			// Standard Error: 31
			.saturating_add(Weight::from_ref_time(15_179 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(6 as u64))
			.saturating_add(T::DbWeight::get().writes(6 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	fn add_secret() -> Weight {
		Weight::from_ref_time(142_948_000 as u64)
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT SecretNftsShardsCount (r:1 w:1)
	fn add_secret_shard() -> Weight {
		Weight::from_ref_time(68_679_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT SecretNftMintFee (r:0 w:1)
	fn set_secret_nft_mint_fee() -> Weight {
		Weight::from_ref_time(28_984_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}

	//TODO CHANGE WITH REAL VALUES
	// Storage: NFT NftMintFee (r:1 w:0)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT NextNFTId (r:1 w:1)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	// Storage: NFT Nfts (r:0 w:1)
	fn create_capsule(_s: u32) -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	fn convert_to_capsule() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	// TODO
	// // Storage: NFT Nfts (r:1 w:1)
	// // Storage: NFT SecretNftMintFee (r:1 w:0)
	// // Storage: System Account (r:1 w:1)
	// // Storage: NFT SecretNftsOffchainData (r:0 w:1)
	// fn revert_capsule() -> Weight {
	// 	Weight::from_ref_time(10_000_000 as u64)
	// }
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	fn set_capsule_offchaindata() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	// Storage: NFT CapsuleMintFee (r:0 w:1)
	fn set_capsule_mint_fee() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	// Storage: NFT CapsuleMintFee (r:0 w:1)
	fn add_capsule_shard() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
	// Storage: NFT CapsuleMintFee (r:0 w:1)
	fn notify_enclave_key_update() -> Weight {
		Weight::from_ref_time(10_000_000 as u64)
	}
}
