[package]
name = "ternoa-runtime-common"
authors = [ "Ternoa" ]
version = "0.1.0"
edition = "2018"

[dependencies]
# Ternoa
ternoa-primitives = { default-features = false, path = "../../primitives" }

[features]
default = ["std"]
std = [
    "ternoa-primitives/std",
]