[package]
name = "ternoa-runtime-common"
authors = [ "Ternoa" ]
version = "0.1.0"
edition = "2018"

[dependencies]
# Ternoa
ternoa-primitives-ternoa = { default-features = false, path = "../../primitives/ternoa" }

[features]
default = ["std"]
std = [
    "ternoa-primitives-ternoa/std",
]