//! Autogenerated weights for `ternoa_nfts`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/ternoa
// benchmark
// --chain
// dev
// --execution=wasm
// --wasm-execution
// compiled
// --extrinsic=*
// --pallet=ternoa_nfts
// --steps=50
// --repeat=20
// --heap-pages=4096
// --output
// .

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
    fn create() -> Weight;
    fn transfer() -> Weight;
    fn burn() -> Weight;
    fn finish_series() -> Weight;
    fn set_nft_mint_fee() -> Weight;
    fn lend() -> Weight;
}


/// Weight functions for `ternoa_nfts`.
pub struct TernoaWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for TernoaWeight<T> {
	// Storage: Nfts NftMintFee (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: Nfts NftIdGenerator (r:1 w:1)
	// Storage: Nfts SeriesIdGenerator (r:1 w:1)
	// Storage: Nfts Series (r:1 w:1)
	// Storage: Nfts Data (r:0 w:1)
	fn create() -> Weight {
		(46_461_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: Nfts Data (r:1 w:1)
	// Storage: Nfts Series (r:1 w:0)
	fn transfer() -> Weight {
		(17_960_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Nfts Data (r:1 w:1)
	fn burn() -> Weight {
		(14_920_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Nfts Series (r:1 w:1)
	fn finish_series() -> Weight {
		(14_170_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Nfts NftMintFee (r:0 w:1)
	fn set_nft_mint_fee() -> Weight {
		(10_100_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Nfts Data (r:1 w:1)
	fn lend() -> Weight {
		(14_870_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
