[package]
name = "ternoa-executor"
version = "0.2.0"
edition = "2018"

[dependencies]
parity-scale-codec = "2.0.1"
ternoa-primitives = { path = "../primitives" }
ternoa-runtime = { path = "../runtime" }
sc-executor = { git = "https://github.com/paritytech/substrate/" }
sp-core = { git = "https://github.com/paritytech/substrate/" }
sp-io = { git = "https://github.com/paritytech/substrate/" }
sp-state-machine = { git = "https://github.com/paritytech/substrate/" }
sp-trie = { git = "https://github.com/paritytech/substrate/" }
trie-root = "0.16.0"
frame-benchmarking = { git = "https://github.com/paritytech/substrate/" }

[features]
wasmtime = [
	"sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []