[package]
name = "ternoa-cli"
authors = [ "Ternoa" ]
edition = "2018"
version = "0.1.0"

[dependencies]

# Ternoa
service = { package = "ternoa-service", path = "../service", default-features = false }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/capsule-corp-ternoa/substrate", branch = "master" }