
//! Autogenerated weights for `ternoa_nft`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-10-18, STEPS: `2`, REPEAT: 1, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `DESKTOP-PAL18UV`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("alphanet-dev"), DB CACHE: 1024

// Executed Command:
// D:\TernoaCode\ternoa-node\target\production\ternoa.exe
// benchmark
// pallet
// --chain=alphanet-dev
// --steps=2
// --repeat=1
// --pallet=ternoa_nft
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output
// ./output

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `ternoa_nft`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> ternoa_nft::WeightInfo for WeightInfo<T> {
	// Storage: NFT NftMintFee (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT NextNFTId (r:1 w:1)
	// Storage: NFT Nfts (r:0 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn create_nft(_s: u32, ) -> Weight {
		Weight::from_ref_time(9_636_100_000 as u64)
			.saturating_add(T::DbWeight::get().reads(5 as u64))
			.saturating_add(T::DbWeight::get().writes(5 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT Collections (r:1 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn burn_nft(_s: u32, ) -> Weight {
		Weight::from_ref_time(10_144_400_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	fn transfer_nft() -> Weight {
		Weight::from_ref_time(24_300_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT DelegatedNFTs (r:0 w:1)
	fn delegate_nft() -> Weight {
		Weight::from_ref_time(42_800_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	fn set_royalty() -> Weight {
		Weight::from_ref_time(26_700_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT NftMintFee (r:0 w:1)
	fn set_nft_mint_fee() -> Weight {
		Weight::from_ref_time(23_900_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT NextCollectionId (r:1 w:1)
	// Storage: NFT Collections (r:0 w:1)
	fn create_collection() -> Weight {
		Weight::from_ref_time(45_300_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	fn burn_collection() -> Weight {
		Weight::from_ref_time(26_400_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	fn close_collection() -> Weight {
		Weight::from_ref_time(32_900_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	fn limit_collection() -> Weight {
		Weight::from_ref_time(26_600_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT Nfts (r:1 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn add_nft_to_collection(_s: u32, ) -> Weight {
		Weight::from_ref_time(13_132_600_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT NftMintFee (r:1 w:0)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: NFT Collections (r:1 w:1)
	// Storage: NFT NextNFTId (r:1 w:1)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	// Storage: NFT Nfts (r:0 w:1)
	/// The range of component `s` is `[0, 999999]`.
	fn create_secret_nft(_s: u32, ) -> Weight {
		Weight::from_ref_time(12_647_800_000 as u64)
			.saturating_add(T::DbWeight::get().reads(6 as u64))
			.saturating_add(T::DbWeight::get().writes(6 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT SecretNftMintFee (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: NFT SecretNftsOffchainData (r:0 w:1)
	fn add_secret() -> Weight {
		Weight::from_ref_time(56_800_000 as u64)
			.saturating_add(T::DbWeight::get().reads(4 as u64))
			.saturating_add(T::DbWeight::get().writes(4 as u64))
	}
	// Storage: NFT Nfts (r:1 w:1)
	// Storage: NFT SecretNftsShardsCount (r:1 w:1)
	fn add_secret_shard() -> Weight {
		Weight::from_ref_time(30_100_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: NFT SecretNftMintFee (r:0 w:1)
	fn set_secret_nft_mint_fee() -> Weight {
		Weight::from_ref_time(23_200_000 as u64)
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}
