name: Build Ubuntu 22.04 Binary

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  call-start-new-build-machine:
    uses: ./.github/workflows/start-new-build-machine.yml
    secrets: inherit

  build:
    runs-on: GP1-M
    name: Build Ubuntu 2204 Binary
    steps:
    - uses: actions/checkout@v3

    - name: "Build DockerImage"
      run: podman build -t tchain -f ./dockerimages/ubuntu-2204-dev.Dockerfile .

    - name: "Create output folder."
      run: mkdir output

    - name: "Run Build Binary Script"
      run: podman run --rm -v ./output:/output -t tchain /bin/bash .github/dockerimages/build-binary.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
        path: output

    