name: Build Wasm

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime'
        required: true
        type: choice
        options:
        - alphanet
        - mainnet

env:
  CARGO_TERM_COLOR: always
  Runtime: ${{ github.event.inputs.runtime }}

jobs:
  call-start-new-build-machine:
    uses: ./.github/workflows/start-new-build-machine.yml
    secrets: inherit

  build:
    runs-on: GP1-M
    name: Build WASM
    steps:
    - uses: actions/checkout@v3

    - name: "Build DockerImage"
      run: podman build -t tchain -f ./.github/dockerimages/dev-ubuntu-22.Dockerfile .

    - name: "Create output folder."
      run: mkdir output

    - name: "Run Build Wasm Script"
      run: |
        export runtime=${{ github.event.inputs.runtime }}
        podman run --rm -e runtime=$runtime -v ./output:/workdir/output -t tchain /bin/bash .github/dockerimages/build-wasm.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
        path: output

    