name: Rust

on:
  push:
    branches: [ soufiane ]
  pull_request:
    branches: [ soufiane ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted 
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release
