name: Rust

on:
  push:
    branches: [ soufiane ]
  pull_request:
    branches: [ soufiane ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ternoa-runner-linux-ubuntu

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --all-targets --all-features --workspace
