name: Run Benchmarks

on:
  workflow_dispatch:
    inputs:
      runtime:
        description: 'Runtime'
        required: true
        type: choice
        options:
        - alphanet
        - mainnet

env:
  CARGO_TERM_COLOR: always
  Runtime: ${{ github.event.inputs.runtime }}

jobs:
  build:
    runs-on: GP1-M
    name: Run Benchmarks
    steps:
    - uses: actions/checkout@v3

    - name: "Build DockerImage"
      run: podman build -t tchain -f ./dockerimages/ubuntu-2204-dev.Dockerfile .

    - name: "Create output folder."
      run: mkdir output

    - name: "Run Benchmarks"
      run: |
        export runtime=${{ github.event.inputs.runtime }}
        podman run --rm -e runtime=$runtime -v ./output:/output -t tchain /bin/bash .github/dockerimages/run-benchmarks.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: assets-for-download
        path: output

    