name: Start New Build Machine

on:
  workflow_call:

jobs:
  start_machine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Run Script"
        run: |
          cd ./.github/scripts
          SCW_SECRET_KEY=${{ secrets.SW_CHAIN_REFERENCE_PROJ_SECRET_KEY }}
          GITHUB_BUILD_MACHINE_TOKEN=${{ secrets.MARKO_PERSONA_TOKEN }}
          ./start-new-machine.sh