name: Turn off all running non-busy build machines

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Run Stop Running Machines Script"
        run: |
          export SCW_SECRET_KEY=${{ secrets.SW_SECRET_ACCESS_KEY }}
          export GITHUB_BUILD_MACHINE_TOKEN=${{ secrets.MARKO_PERSONA_TOKEN }}
          cd ./.github/scripts
          ./stop-one-machine.sh